### ISSUE TITLE
Using LiteLLM + Ollama to run this locally with the Sample data & getting Assertion Error

### ISSUE THREAD

**Issue by KuriaMaingi** [FireBird-Technologies/Auto-Analyst-Streamlit#2]
It makes the call just fine to the llm

LLM Proxy initialised with:
litellm --model ollama/gemma2:latest --temperature 0 --drop_params
LiteLLM output: 
`INFO:     172.24.80.1:24632 - "POST /completions HTTP/1.1" 200 OK`

Ollama is serving the model on WSL Ubuntu
Ollama output:
`
INFO [main] model loaded | tid="140637699522560" timestamp=1723460379
time=2024-08-12T13:59:39.202+03:00 level=INFO source=server.go:622 msg="llama runner started in 44.96 seconds"
INFO [update_slots] input truncated | n_ctx=2048 n_erase=2875 n_keep=4 n_left=2044 n_shift=1022 tid="140637699522560" timestamp=1723460379
[GIN] 2024/08/12 - 13:59:40 | 200 | 47.356970067s |       127.0.0.1 | POST     "/api/generate"
INFO [update_slots] input truncated | n_ctx=2048 n_erase=2875 n_keep=4 n_left=2044 n_shift=1022 tid="140637699522560" timestamp=1723460380
[GIN] 2024/08/12 - 13:59:40 | 200 |  185.233863ms |       127.0.0.1 | POST     "/api/generate"
INFO [update_slots] input truncated | n_ctx=2048 n_erase=2879 n_keep=4 n_left=2044 n_shift=1022 tid="140637699522560" timestamp=1723460380
[GIN] 2024/08/12 - 13:59:41 | 200 |  735.609286ms |       127.0.0.1 | POST     "/api/generate"
`

DSPY OpenAPI compliant object created as below:
`dspy.configure(lm` = dspy.OpenAI(model='gemma2:latest', api_key=os.environ['OPENAI_API_KEY'], api_base=os.environ["LLM_BASE_URL"], max_tokens=8128))`

My guess is that somehow there is a chat template difference and the response is being discarded as a result

Application Error:
`
Uncaught app exception
Traceback (most recent call last):
  File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "G:\Projects\Auto-Analyst\new_frontend.py", line 353, in <module>
    run_chat()
  File "G:\Projects\Auto-Analyst\new_frontend.py", line 219, in run_chat
    output=st.session_state['agent_system_chat'](query=user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dspy\primitives\program.py", line 26, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects\Auto-Analyst\agents.py", line 406, in forward
    plan = self.planner(goal =dict_['goal'], dataset=dict_['dataset'], Agent_desc=dict_['Agent_desc'] )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dspy\predict\predict.py", line 61, in __call__
    return self.forward(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dspy\predict\chain_of_thought.py", line 59, in forward
    return super().forward(signature=signature, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dspy\predict\predict.py", line 103, in forward
    x, C = dsp.generate(template, **config)(x, stage=self.stage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dsp\primitives\predict.py", line 120, in do_generate
    return generate(template, **new_kwargs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dsp\primitives\predict.py", line 120, in do_generate
    return generate(template, **new_kwargs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dsp\primitives\predict.py", line 119, in do_generate
    assert max_depth > 0
           ^^^^^^^^^^^^^
AssertionError
`

**Comment by ArslanS1997** [comment]
> It makes the call just fine to the llm
> 
> LLM Proxy initialised with:
> litellm --model ollama/gemma2:latest --temperature 0 --drop_params
> LiteLLM output: 
> `INFO:     172.24.80.1:24632 - "POST /completions HTTP/1.1" 200 OK`
> 
> Ollama is serving the model on WSL Ubuntu
> Ollama output:
> `
> INFO [main] model loaded | tid="140637699522560" timestamp=1723460379
> time=2024-08-12T13:59:39.202+03:00 level=INFO source=server.go:622 msg="llama runner started in 44.96 seconds"
> INFO [update_slots] input truncated | n_ctx=2048 n_erase=2875 n_keep=4 n_left=2044 n_shift=1022 tid="140637699522560" timestamp=1723460379
> [GIN] 2024/08/12 - 13:59:40 | 200 | 47.356970067s |       127.0.0.1 | POST     "/api/generate"
> INFO [update_slots] input truncated | n_ctx=2048 n_erase=2875 n_keep=4 n_left=2044 n_shift=1022 tid="140637699522560" timestamp=1723460380
> [GIN] 2024/08/12 - 13:59:40 | 200 |  185.233863ms |       127.0.0.1 | POST     "/api/generate"
> INFO [update_slots] input truncated | n_ctx=2048 n_erase=2879 n_keep=4 n_left=2044 n_shift=1022 tid="140637699522560" timestamp=1723460380
> [GIN] 2024/08/12 - 13:59:41 | 200 |  735.609286ms |       127.0.0.1 | POST     "/api/generate"
> `
> 
> DSPY OpenAPI compliant object created as below:
> `dspy.configure(lm` = dspy.OpenAI(model='gemma2:latest', api_key=os.environ['OPENAI_API_KEY'], api_base=os.environ["LLM_BASE_URL"], max_tokens=8128))`
> 
> My guess is that somehow there is a chat template difference and the response is being discarded as a result
> 
> Application Error:
> `
> Uncaught app exception
> Traceback (most recent call last):
>   File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
>     exec(code, module.__dict__)
>   File "G:\Projects\Auto-Analyst\new_frontend.py", line 353, in <module>
>     run_chat()
>   File "G:\Projects\Auto-Analyst\new_frontend.py", line 219, in run_chat
>     output=st.session_state['agent_system_chat'](query=user_input)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dspy\primitives\program.py", line 26, in __call__
>     return self.forward(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\Projects\Auto-Analyst\agents.py", line 406, in forward
>     plan = self.planner(goal =dict_['goal'], dataset=dict_['dataset'], Agent_desc=dict_['Agent_desc'] )
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dspy\predict\predict.py", line 61, in __call__
>     return self.forward(**kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dspy\predict\chain_of_thought.py", line 59, in forward
>     return super().forward(signature=signature, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dspy\predict\predict.py", line 103, in forward
>     x, C = dsp.generate(template, **config)(x, stage=self.stage)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dsp\primitives\predict.py", line 120, in do_generate
>     return generate(template, **new_kwargs)(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dsp\primitives\predict.py", line 120, in do_generate
>     return generate(template, **new_kwargs)(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dsp\primitives\predict.py", line 119, in do_generate
>     assert max_depth > 0
>            ^^^^^^^^^^^^^
> AssertionError
> `

So you're using OpenAI not OpenAPi

**Comment by KuriaMaingi** [comment]
> So you're using OpenAI not OpenAPi

Yes correct. What is the distinction there?

The reason I was going this route (OpenAI compliant proxy) is that running with dspy.OllamaLocal(...) causes a different error namely:

'Traceback (most recent call last):
  File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "G:\Projects\Auto-Analyst\new_frontend.py", line 353, in <module>
    run_chat()
  File "G:\Projects\Auto-Analyst\new_frontend.py", line 219, in run_chat
    output=st.session_state['agent_system_chat'](query=user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects\Auto-Analyst\.venv\Lib\site-packages\dspy\primitives\program.py", line 26, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Projects\Auto-Analyst\agents.py", line 436, in forward
    inputs = {x:dict_[x] for x in self.agent_inputs[p.strip()]}
                                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: ''
`

**Comment by ArslanS1997** [comment]
Lemme investigate and get back to you, tell me what LLM were you using via Ollama?

**Comment by KuriaMaingi** [comment]
Gemma2 9B [https://ollama.com/library/gemma2](url)

**Comment by ArslanS1997** [comment]
Hi so I investigated the error happens when the LLM does not output a correct name for the agent, this was a planner based query, so basically the planner outputted "" instead of say "agent_name", which caused an error.

Would recommend a more powerful LM like Llama 3.1 for opensource models

**Comment by KuriaMaingi** [comment]
Great. Got it working with Gemini 1.5 pro which still fails on certain queries, will give the rest a try
