### ISSUE TITLE
Injecting Domain Knowledge into the Agent system

### ISSUE THREAD

**Issue by tranhoangnguyen03** [FireBird-Technologies/Auto-Analyst-Streamlit#3]
Hi,

I am very impressed by your work here. I find the way you set up your agents very compelling, and the use of DSPy allows for a very clean and easy to understand agent definition and orchestration. I have been using LangChain and LangGraph to basically achieve the same goal as you (Business Intelligence Analyst Bot), and I must say that I am very tempted to give in to your DSPy way; or at least find a way to marry LangGraph with DSPy.

Anyhow, in my project, I need to inject some domain knowledge (a dictionary of abbreviations and org-specific terminologies as well as their business contexts) into the agentic flow. I achieve this by having a dedicated librarian agent who performs similarity lookup the question (containing the terminologies) against the domain knowledge bm25 embedding. The librarian agent then give hints to the planner query.

I hope it's useful to you. I'd love to hear your take on this, and will be keeping an eye out for this high potential project of yours.

Cheers,

**Comment by ArslanS1997** [comment]
Hi Thanks for your kind words and the librarian approach you suggested. I believe it could be tremendously useful.

:thumbsup:
