### ISSUE TITLE
Auto analyst on colab

### ISSUE THREAD

**Issue by DarrenDsouza47** [FireBird-Technologies/Auto-Analyst-Streamlit#4]
Hi, i have tried to implement this application on colab as a demo but i keep getting this same error from planner agent

![image](https://github.com/user-attachments/assets/2a9bb179-7116-4135-b2a8-7b95a8548149)
 
i have tried two ways to passing dataset

![image](https://github.com/user-attachments/assets/d270839c-6de7-42fb-af68-93ea32b290b5)

![image](https://github.com/user-attachments/assets/3e6177ee-1239-4a8c-ad11-7de461e22a70)

But i keep getting the same error

Settings.embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-small-en-v1.5"
)

this is the embedding I have used for llama index

**Comment by ArslanS1997** [comment]
What is the query you're feeding and LLM you're using

**Comment by DarrenDsouza47** [comment]
model:
![image](https://github.com/user-attachments/assets/396bfb26-bf98-448f-8879-91906b0cd97a)

query:
![image](https://github.com/user-attachments/assets/0970a153-342e-434f-8a06-b03a00039cd0)

**Comment by ArslanS1997** [comment]
Try with a model with longer context window. 

Llama 3 has short context. So that is causing the problem.

**Comment by DarrenDsouza47** [comment]
I tried llama3.1 and llama-gradient with 128k context window but it seems the error still persists

![image](https://github.com/user-attachments/assets/2eeea25c-8f01-4b91-97d1-8a0bdc6a850a)

![image](https://github.com/user-attachments/assets/ed7c16cc-eb17-462f-ab8b-1cdfac62f19f)

**Comment by ArslanS1997** [comment]
Hi I think dspy by default restricts LLMs to 300 tokens.

In your line where you initialize the LLM add max_tokens =10000

**Comment by DarrenDsouza47** [comment]
Yes default was 150 tokens for ollama
![image](https://github.com/user-attachments/assets/f690ccef-9064-4a25-887c-b24054827f15)

but running into another issue:
![image](https://github.com/user-attachments/assets/cdf11c4d-cd5c-4683-acd9-641ad8f969f6)


this i think involves model's accuracy ,openai seems the only good model for this task

i have used llama3.1-8b-instruct GGUF

**Comment by ArslanS1997** [comment]
HI you should go to the agent definitions and use an LLM to summarize the prompts. They were designed for long context models like ChatGPT 4o. Also change from ChainOfThought to Predict. 

It will help you. Also try using llama3-70B using Groq

**Comment by ArslanS1997** [comment]
Because the answer is correct the Model is just not outputting the structure accurately. By changing from ChainOfThought to dspy.Predict() you won't have the rationale output anymore

**Comment by ArslanS1997** [comment]
Closing
